### ISSUE TITLE
Please free unused domain name `hackcat.me` 

### ISSUE THREAD

**Issue by HackcatDev** [HackaCat/HackaCat.github.io#1]
Hello man!

I see you took a domain name with my nickname. I don't see it's really used so I kindly ask to free it. I used my nickname for years so it's at least not honest to use this nickname in domain names without permission.

Thanks for your attention!

**Comment by HackaCat** [comment]
This domain will be in use shortly. HackCat is a handle I also have been using for many years, and a domain I was able to acquire recently, fairly and without issue. 

I will not be releasing this domain at this time. I appreciate that it is also a nickname that you have used - however, duplicates are likely to happen on the internet and we must be ready to deal with them. Just ask Nissan.
